export default [
    {task:'Fazer Tarefa', done: false},
    {task:'Fazer ABC', done:true},
    {task:'Fazer Exercicio', done:false},
    {task:'Fazer BCD', done:false},
    {task:'Fazer Tarefa', done: false},
    {task:'Fazer ABC', done:true},
    {task:'Fazer Exercicio', done:false},
    {task:'Fazer BCD', done:false},
    {task:'Fazer Tarefa', done: false},
    {task:'Fazer ABC', done:true},
    {task:'Fazer Exercicio', done:false},
    {task:'Fazer BCD', done:false},
    {task:'Fazer Tarefa', done: false},
    {task:'Fazer ABC', done:true},
    {task:'Fazer Exercicio', done:false},
    {task:'Fazer BCD', done:false},
    {task:'Fazer Tarefa', done: false},
    {task:'Fazer ABC', done:true},
    {task:'Fazer Exercicio', done:false},
    {task:'Fazer BCD', done:false},
    {task:'Fazer Tarefa', done: false},
    {task:'Fazer ABC', done:true},
    {task:'Fazer Exercicio', done:false},
    {task:'Fazer BCD', done:false},
];